import type { PlatformCategory, PlatformDef, RotateKind } from "./types";

export const PLATFORMS: PlatformDef[] = [
  {
    id: "infisical",
    name: "Infisical",
    category: "secrets",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["st.", "infisical_"],
    nameHints: ["INFISICAL"],
    docsUrl: "https://infisical.com/docs/api-reference/overview/introduction",
    hint: "Upserts rotated values into the connected project and environment.",
    generator: "hex-64",
  },
  {
    id: "vault",
    name: "HashiCorp Vault",
    category: "secrets",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["hvs.", "s."],
    nameHints: ["VAULT", "HCP_VAULT"],
    docsUrl: "https://developer.hashicorp.com/vault/docs",
    hint: "Generate a new token in Vault, then write destinations.",
    generator: "hex-64",
  },
  {
    id: "doppler",
    name: "Doppler",
    category: "secrets",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["dp.ct.", "dp.pt."],
    nameHints: ["DOPPLER"],
    docsUrl: "https://docs.doppler.com/reference",
    hint: "Service tokens are issued in Doppler; TopSpin fans the new value out.",
    generator: "hex-64",
  },
  {
    id: "onepassword",
    name: "1Password Connect",
    category: "secrets",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["ops_", "opw_"],
    nameHints: ["OP_", "ONEPASSWORD"],
    docsUrl: "https://developer.1password.com/",
    hint: "Connect tokens are issued in 1Password; history lands in Keychain.",
    generator: "hex-64",
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    cadenceDays: 60,
    rotateKind: "live-api",
    prefixes: ["sk-"],
    nameHints: ["OPENAI"],
    docsUrl: "https://platform.openai.com/api-keys",
    hint: "Creates a new project/admin key when an admin key is in the vault.",
    generator: "hex-64",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "ai",
    cadenceDays: 60,
    rotateKind: "manual",
    prefixes: ["sk-ant-"],
    nameHints: ["ANTHROPIC", "CLAUDE"],
    docsUrl: "https://console.anthropic.com/settings/keys",
    hint: "Issue a new key in the Anthropic console, then Spin to fan it out.",
    generator: "hex-64",
  },
  {
    id: "xai",
    name: "xAI",
    category: "ai",
    cadenceDays: 60,
    rotateKind: "manual",
    prefixes: ["xai-"],
    nameHints: ["XAI", "GROK"],
    docsUrl: "https://console.x.ai/",
    hint: "Issue a new xAI key, then write Infisical, file, and Keychain.",
    generator: "hex-64",
  },
  {
    id: "groq",
    name: "Groq",
    category: "ai",
    cadenceDays: 60,
    rotateKind: "manual",
    prefixes: ["gsk_"],
    nameHints: ["GROQ"],
    docsUrl: "https://console.groq.com/keys",
    hint: "Create a Groq key, then fan out through destinations.",
    generator: "hex-64",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "ai",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["hf_"],
    nameHints: ["HF_", "HUGGINGFACE"],
    docsUrl: "https://huggingface.co/settings/tokens",
    hint: "Creates a new fine-grained token using the current one, then revokes the old.",
    generator: "hex-64",
  },
  {
    id: "google-ai",
    name: "Google AI / Gemini",
    category: "ai",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["AIza"],
    nameHints: ["GEMINI", "GOOGLE_AI", "GENERATIVE"],
    docsUrl: "https://aistudio.google.com/apikey",
    hint: "Google API keys are issued in AI Studio or Cloud Console.",
    generator: "hex-64",
  },
  {
    id: "github",
    name: "GitHub",
    category: "git",
    cadenceDays: 60,
    rotateKind: "live-api",
    prefixes: ["ghp_", "github_pat_", "gho_", "ghu_", "ghs_"],
    nameHints: ["GITHUB", "GH_TOKEN", "GH_PAT"],
    docsUrl: "https://github.com/settings/tokens",
    hint: "Uses the token to rewrite Actions / Dependabot secrets. PATs themselves are issued on GitHub.",
    generator: "hex-64",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "git",
    cadenceDays: 60,
    rotateKind: "manual",
    prefixes: ["glpat-"],
    nameHints: ["GITLAB"],
    docsUrl: "https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html",
    hint: "Create a new PAT in GitLab, then Spin to update destinations.",
    generator: "hex-64",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "git",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["BITBUCKET"],
    docsUrl: "https://support.atlassian.com/bitbucket-cloud/",
    hint: "App passwords are created in Bitbucket settings.",
    generator: "password-32",
  },
  {
    id: "aws",
    name: "AWS IAM",
    category: "cloud",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["AKIA"],
    nameHints: ["AWS_ACCESS", "AWS_SECRET"],
    docsUrl: "https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html",
    hint: "Creates a new access key for the same IAM user, then optionally deletes the old.",
    generator: "password-32",
  },
  {
    id: "gcp",
    name: "Google Cloud",
    category: "cloud",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["GCP", "GOOGLE_CLOUD", "GCLOUD"],
    docsUrl: "https://cloud.google.com/iam/docs/keys-create-delete",
    hint: "Mint a new service-account key in Cloud Console, then fan it out.",
    generator: "base64-48",
  },
  {
    id: "azure",
    name: "Azure",
    category: "cloud",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["AZURE", "ARM_"],
    docsUrl: "https://learn.microsoft.com/en-us/azure/key-vault/",
    hint: "Rotate client secrets in Entra ID, then write destinations.",
    generator: "password-32",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cloud",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: [],
    nameHints: ["CLOUDFLARE", "CF_API", "CF_TOKEN"],
    docsUrl: "https://developers.cloudflare.com/fundamentals/api/how-to/create-via-api/",
    hint: "Rolls the current API token value in place when the token allows it.",
    generator: "hex-64",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: [],
    nameHints: ["VERCEL"],
    docsUrl: "https://vercel.com/docs/rest-api",
    hint: "Creates a new token and can rewrite project environment variables.",
    generator: "hex-64",
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["nfp_"],
    nameHints: ["NETLIFY"],
    docsUrl: "https://docs.netlify.com/api/get-started/",
    hint: "Personal access tokens are issued in Netlify user settings.",
    generator: "hex-64",
  },
  {
    id: "railway",
    name: "Railway",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["RAILWAY"],
    docsUrl: "https://docs.railway.app/",
    hint: "Account tokens are issued in Railway. Fan-out is handled here.",
    generator: "hex-64",
  },
  {
    id: "render",
    name: "Render",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["rnd_"],
    nameHints: ["RENDER"],
    docsUrl: "https://api-docs.render.com/",
    hint: "API keys are created in the Render dashboard.",
    generator: "hex-64",
  },
  {
    id: "fly",
    name: "Fly.io",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["fo1_"],
    nameHints: ["FLY_"],
    docsUrl: "https://fly.io/docs/",
    hint: "Create an org token with fly tokens create, then Spin.",
    generator: "hex-64",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["dop_v1_"],
    nameHints: ["DIGITALOCEAN", "DO_API", "DO_TOKEN"],
    docsUrl: "https://docs.digitalocean.com/reference/api/",
    hint: "Personal tokens are issued in the DigitalOcean control panel.",
    generator: "hex-64",
  },
  {
    id: "coolify",
    name: "Coolify",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["COOLIFY"],
    docsUrl: "https://coolify.io/docs/",
    hint: "Rotate the Coolify API token, then write it to the Mac and Infisical.",
    generator: "hex-64",
  },
  {
    id: "heroku",
    name: "Heroku",
    category: "hosting",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["HRKU-"],
    nameHints: ["HEROKU"],
    docsUrl: "https://devcenter.heroku.com/",
    hint: "API keys live in Heroku account settings.",
    generator: "hex-64",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["sk_live_", "sk_test_", "rk_live_", "rk_test_", "whsec_"],
    nameHints: ["STRIPE"],
    docsUrl: "https://dashboard.stripe.com/apikeys",
    hint: "Creates a restricted key via the Stripe API when an admin secret is in the vault.",
    generator: "hex-64",
  },
  {
    id: "slack",
    name: "Slack",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["xoxb-", "xoxp-", "xoxa-", "xoxs-"],
    nameHints: ["SLACK"],
    docsUrl: "https://api.slack.com/authentication/rotation",
    hint: "Calls auth.rotate when the token supports refresh-token rotation.",
    generator: "hex-64",
  },
  {
    id: "discord",
    name: "Discord",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["MT", "Bot "],
    nameHints: ["DISCORD"],
    docsUrl: "https://discord.com/developers/applications",
    hint: "Reset the bot token in the Discord developer portal, then Spin.",
    generator: "hex-64",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["SK"],
    nameHints: ["TWILIO"],
    docsUrl: "https://www.twilio.com/docs/iam/keys/api-key",
    hint: "Creates a new API key with the Account SID + Auth Token pair.",
    generator: "hex-64",
  },
  {
    id: "resend",
    name: "Resend",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["re_"],
    nameHints: ["RESEND"],
    docsUrl: "https://resend.com/api-keys",
    hint: "Creates a new sending API key, then optionally deletes the previous one.",
    generator: "hex-64",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["SG."],
    nameHints: ["SENDGRID"],
    docsUrl: "https://docs.sendgrid.com/api-reference/api-keys/",
    hint: "Creates a new API key with the current key, then deletes the old.",
    generator: "hex-64",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["key-"],
    nameHints: ["MAILGUN"],
    docsUrl: "https://documentation.mailgun.com/",
    hint: "Private API keys are rotated in the Mailgun dashboard.",
    generator: "hex-64",
  },
  {
    id: "postmark",
    name: "Postmark",
    category: "comms",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["POSTMARK"],
    docsUrl: "https://postmarkapp.com/developer",
    hint: "Server tokens are issued per Postmark server.",
    generator: "hex-64",
  },
  {
    id: "neon",
    name: "Neon",
    category: "data",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: [],
    nameHints: ["NEON"],
    docsUrl: "https://api-docs.neon.tech/",
    hint: "Creates a new org API key when the current key can mint one.",
    generator: "hex-64",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "data",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["sbp_", "sb_publishable_", "sb_secret_"],
    nameHints: ["SUPABASE"],
    docsUrl: "https://supabase.com/docs",
    hint: "Service-role and PAT values are issued in the Supabase dashboard.",
    generator: "hex-64",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "data",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["pscale_tkn_"],
    nameHints: ["PLANETSCALE"],
    docsUrl: "https://api-docs.planetscale.com/",
    hint: "Service tokens are created in PlanetScale settings.",
    generator: "hex-64",
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas",
    category: "data",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["MONGODB", "MONGO_"],
    docsUrl: "https://www.mongodb.com/docs/atlas/configure-api-access/",
    hint: "Programmatic API keys rotate in Atlas Access Manager.",
    generator: "password-32",
  },
  {
    id: "fmp",
    name: "Financial Modeling Prep",
    category: "data",
    cadenceDays: 180,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["FMP"],
    docsUrl: "https://site.financialmodelingprep.com/developer/docs",
    hint: "Dashboard-issued key. TopSpin will still rewrite every destination.",
    generator: "hex-32",
  },
  {
    id: "npm",
    name: "npm",
    category: "other",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["npm_", "//registry.npmjs.org/:_authToken="],
    nameHints: ["NPM"],
    docsUrl: "https://docs.npmjs.com/creating-and-viewing-access-tokens",
    hint: "Mints a granular access token via the npm API when the current token allows it.",
    generator: "hex-64",
  },
  {
    id: "docker",
    name: "Docker Hub",
    category: "other",
    cadenceDays: 90,
    rotateKind: "live-api",
    prefixes: ["dckr_pat_"],
    nameHints: ["DOCKER"],
    docsUrl: "https://docs.docker.com/security/for-developers/access-tokens/",
    hint: "Creates a Docker Hub access token when username + password/PAT are in the vault.",
    generator: "hex-64",
  },
  {
    id: "ssh",
    name: "SSH keys",
    category: "other",
    cadenceDays: 365,
    rotateKind: "generate",
    prefixes: ["-----BEGIN"],
    nameHints: ["SSH", "ED25519"],
    docsUrl: "https://www.openssh.com/",
    hint: "Generates a new Ed25519 key pair in the vault and writes the private key to the Mac agent.",
    generator: "ssh",
  },
  {
    id: "database",
    name: "Database password",
    category: "data",
    cadenceDays: 90,
    rotateKind: "generate",
    prefixes: [],
    nameHints: ["DATABASE_PASSWORD", "DB_PASSWORD", "POSTGRES_PASSWORD", "MYSQL_PASSWORD"],
    docsUrl: "",
    hint: "Generates a high-entropy password. Apply it on the database, then destinations.",
    generator: "password-32",
  },
  {
    id: "webhook",
    name: "Webhook / HMAC",
    category: "other",
    cadenceDays: 180,
    rotateKind: "generate",
    prefixes: ["whsec_"],
    nameHints: ["WEBHOOK", "HMAC", "SIGNING_SECRET"],
    docsUrl: "",
    hint: "Generates a new signing secret and writes it everywhere you keep it.",
    generator: "hex-64",
  },
  {
    id: "jwt",
    name: "JWT signing key",
    category: "other",
    cadenceDays: 180,
    rotateKind: "generate",
    prefixes: [],
    nameHints: ["JWT_SECRET", "NEXTAUTH_SECRET", "SESSION_SECRET", "AUTH_SECRET"],
    docsUrl: "",
    hint: "Generates a new 64-byte signing secret.",
    generator: "hex-64",
  },
  {
    id: "apple-keychain",
    name: "Apple Keychain",
    category: "apple",
    cadenceDays: 365,
    rotateKind: "generate",
    prefixes: [],
    nameHints: ["KEYCHAIN"],
    docsUrl: "https://support.apple.com/guide/keychain-access/",
    hint: "Current values and dated history items are written via the Mac agent.",
    generator: "password-32",
  },
  {
    id: "apple-asc",
    name: "App Store Connect",
    category: "apple",
    cadenceDays: 180,
    rotateKind: "manual",
    prefixes: [],
    nameHints: ["APPSTORE", "ASC_", "APPLE_API"],
    docsUrl: "https://developer.apple.com/documentation/appstoreconnectapi",
    hint: "Issue a new .p8 key in App Store Connect, then store it in Keychain and Infisical.",
    generator: "hex-64",
  },
  {
    id: "linear",
    name: "Linear",
    category: "other",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["lin_api_"],
    nameHints: ["LINEAR"],
    docsUrl: "https://developers.linear.app/",
    hint: "Personal API keys are created in Linear settings.",
    generator: "hex-64",
  },
  {
    id: "notion",
    name: "Notion",
    category: "other",
    cadenceDays: 90,
    rotateKind: "manual",
    prefixes: ["ntn_", "secret_"],
    nameHints: ["NOTION"],
    docsUrl: "https://developers.notion.com/",
    hint: "Internal integration tokens rotate in the Notion integrations page.",
    generator: "hex-64",
  },
  {
    id: "generic",
    name: "Generic secret",
    category: "other",
    cadenceDays: 90,
    rotateKind: "generate",
    prefixes: [],
    nameHints: [],
    docsUrl: "",
    hint: "High-entropy replacement, then write every connected destination.",
    generator: "hex-64",
  },
];

export const PLATFORM_BY_ID: Record<string, PlatformDef> = Object.fromEntries(
  PLATFORMS.map((p) => [p.id, p]),
);

export const CATEGORY_LABEL: Record<PlatformCategory, string> = {
  secrets: "Secret managers",
  ai: "AI",
  git: "Git",
  cloud: "Cloud",
  hosting: "Hosting",
  payments: "Payments",
  comms: "Communications",
  data: "Data",
  apple: "Apple",
  other: "Other",
};

export function detectPlatform(name: string, value: string): string {
  const n = name.toUpperCase();
  const v = value.trim();

  for (const p of PLATFORMS) {
    if (p.id === "generic") continue;
    if (p.prefixes.some((pre) => pre && v.startsWith(pre))) return p.id;
  }
  for (const p of PLATFORMS) {
    if (p.id === "generic") continue;
    if (p.nameHints.some((h) => n.includes(h))) return p.id;
  }
  return "generic";
}

export function platformOf(id: string): PlatformDef {
  return PLATFORM_BY_ID[id] ?? PLATFORM_BY_ID.generic;
}

export function rotateKindLabel(kind: RotateKind): string {
  if (kind === "live-api") return "Live API";
  if (kind === "generate") return "Generate";
  return "Console";
}
